version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: t_shirt_orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DATABASE: t_shirt_orders
      ADMINER_USERNAME: user
      ADMINER_PASSWORD: password
volumes:
  postgres_data:
